### ISSUE TITLE
"Capacity" ratio of your vector needs review

### ISSUE THREAD

**Issue by hellovai** [letsago/Coding-Projects#2]
If I always use a factor of 10x, what happens if allocate a vector for the 1,000,000'th element, after having space for 999,999,999? How much memory will you end up requiring just for the new element?

What are the trade offs between using different scale factors?

**Comment by letsago** [comment]
Using 10x spends a lot of memory when implementing memory for high orders of elements. 2x is smallest and most feasible static factor. However, a dynamic factor that scales inversely with size of old vector could work too since we don't want to exhaust so much memory for much higher order sized vectors.

**Comment by hellovai** [comment]
link to pull request
