### ISSUE TITLE
Why are we allocating more memory than we need?

### ISSUE THREAD

**Issue by hellovai** [letsago/Coding-Projects#3]
https://github.com/letsago/Coding-Projects/blob/d33d41edd00299c6992eac431feb8698d1f131c9/Practice/PigLatin/headers/myvector_class.h#L25

**Comment by letsago** [comment]
We're allocating more memory than we need so that way, when user wants to insert new values into vector, we don't have to recopy everything into a new vector that only has enough memory to hold (old_size + 1) values. Allocating more memory than needed reduces amount of memory being called for future vectors.
